<a href="https://colab.research.google.com/github/MehulLuthra/COGNITIVE_COMPUTING/blob/main/ASSIGNMENTTT4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import numpy as np
a=np.array([1,2,3,4,5])
a=a+2
a

array([3, 4, 5, 6, 7])

In [6]:
a=a*3
a

array([ 9, 12, 15, 18, 21])

In [7]:
a=a/2
a

array([ 4.5,  6. ,  7.5,  9. , 10.5])

In [9]:
arr=np.array([1,2,3,6,4,5])
print(arr[::-1])

[5 4 6 3 2 1]


In [13]:
x=np.array([1,2,3,4,5,1,2,1,1,1])
y=np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])
unique_x, counts_x = np.unique(x, return_counts=True)
max_count_index_x = np.argmax(counts_x)
most_freq_x = unique_x[max_count_index_x]
indices_x = np.where(x == most_freq_x)[0]

unique_y, counts_y = np.unique(y, return_counts=True)
max_count_index_y = np.argmax(counts_y)
most_freq_y = unique_y[max_count_index_y]
indices_y = np.where(y == most_freq_y)[0]

print("Most Frequent in x:", most_freq_x, "at indices", indices_x)
print("Most Frequent in y:", most_freq_y, "at indices", indices_y)

Most Frequent in x: 1 at indices [0 5 7 8 9]
Most Frequent in y: 1 at indices [0 1 2]


In [11]:
arr = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

element_a = arr[0, 1]
element_b = arr[2, 0]

print("Element at (1st row, 2nd column):", element_a)
print("Element at (3rd row, 1st column):", element_b)


Element at (1st row, 2nd column): 20
Element at (3rd row, 1st column): 70


In [12]:
my_array = np.linspace(10, 100, 25)


print("Array:", my_array)
print("Shape of the array:", my_array.shape)
print("Total elements in the array:", my_array.size)
print("Data type of each element:", my_array.dtype)
print("Total bytes consumed by the array:", my_array.nbytes)


transposed_array = my_array.reshape(25, 1)
print("\nTransposed Array using reshape():\n", transposed_array)

transposed_using_T = my_array.T
print("\nTransposed using T attribute:\n", transposed_using_T)



Array: [ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]
Shape of the array: (25,)
Total elements in the array: 25
Data type of each element: float64
Total bytes consumed by the array: 200

Transposed Array using reshape():
 [[ 10.  ]
 [ 13.75]
 [ 17.5 ]
 [ 21.25]
 [ 25.  ]
 [ 28.75]
 [ 32.5 ]
 [ 36.25]
 [ 40.  ]
 [ 43.75]
 [ 47.5 ]
 [ 51.25]
 [ 55.  ]
 [ 58.75]
 [ 62.5 ]
 [ 66.25]
 [ 70.  ]
 [ 73.75]
 [ 77.5 ]
 [ 81.25]
 [ 85.  ]
 [ 88.75]
 [ 92.5 ]
 [ 96.25]
 [100.  ]]

Transposed using T attribute:
 [ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]


In [15]:
ucs420_Mehul = np.array([[10, 20, 30, 40], [50, 60, 70, 80], [90, 15, 20, 35]])

mean_val = np.mean(ucs420_Mehul)
median_val = np.median(ucs420_Mehul)
max_val = np.max(ucs420_Mehul)
min_val = np.min(ucs420_Mehul)
unique_vals = np.unique(ucs420_Mehul)

reshaped_ucs420_Mehul = ucs420_Mehul.reshape(4, 3)
resized_ucs420_Mehul = ucs420_Mehul[:2, :3]

print("Mean:", mean_val)
print("Median:", median_val)
print("Max:", max_val)
print("Min:", min_val)
print("Unique Elements:", unique_vals)
print("Original:\n",ucs420_Mehul)
print("Reshaped (4x3):\n", reshaped_ucs420_Mehul)
print("Resized (2x3):\n", resized_ucs420_Mehul)

Mean: 43.333333333333336
Median: 37.5
Max: 90
Min: 10
Unique Elements: [10 15 20 30 35 40 50 60 70 80 90]
Original:
 [[10 20 30 40]
 [50 60 70 80]
 [90 15 20 35]]
Reshaped (4x3):
 [[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]]
Resized (2x3):
 [[10 20 30]
 [50 60 70]]
